#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/tissot

PRODUCT_COPY_FILES += \
    vendor/xiaomi/tissot/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/xiaomi/tissot/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/xiaomi/tissot/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/xiaomi/tissot/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/xiaomi/tissot/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/xiaomi/tissot/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/xiaomi/tissot/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/xiaomi/tissot/proprietary/vendor/etc/acdbdata/QRD/QRD_adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_adsp_avs_config.acdb \
    vendor/xiaomi/tissot/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/ov12a10_arc_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov12a10_arc_chromatix.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/ov12a10_arc_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov12a10_arc_ofilm_chromatix.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/ov12a10_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov12a10_chromatix.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/ov13880_arc_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13880_arc_chromatix.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/ov13880_arc_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13880_arc_ofilm_chromatix.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/ov13880_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13880_chromatix.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/ov5675_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov5675_qtech_chromatix.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/camera/s5k5e8_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e8_ofilm_chromatix.xml \
    vendor/xiaomi/tissot/proprietary/vendor/etc/permissions/com.fingerprints.extension.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.fingerprints.extension.xml

PRODUCT_PACKAGES += \
    gatekeeper.msm8953 \
    keystore.msm8953 \
    libactuator_dw9763 \
    libactuator_dw9763_ofilm_ov12a10 \
    libactuator_dw9763_ofilm_ov13880 \
    libactuator_dw9763_ov12a10 \
    libactuator_dw9763_ov13880 \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_ov12a10_4k_preview_dw9763 \
    libchromatix_ov12a10_4k_video_dw9763 \
    libchromatix_ov12a10_arc_4k_preview_dw9763 \
    libchromatix_ov12a10_arc_4k_video_dw9763 \
    libchromatix_ov12a10_arc_common \
    libchromatix_ov12a10_arc_cpp_hfr_120 \
    libchromatix_ov12a10_arc_cpp_hfr_60 \
    libchromatix_ov12a10_arc_cpp_hfr_90 \
    libchromatix_ov12a10_arc_cpp_liveshot \
    libchromatix_ov12a10_arc_cpp_preview \
    libchromatix_ov12a10_arc_cpp_snapshot \
    libchromatix_ov12a10_arc_cpp_snapshot_hht \
    libchromatix_ov12a10_arc_cpp_video \
    libchromatix_ov12a10_arc_cpp_video_4k \
    libchromatix_ov12a10_arc_default_preview_dw9763 \
    libchromatix_ov12a10_arc_default_video_dw9763 \
    libchromatix_ov12a10_arc_hfr_120 \
    libchromatix_ov12a10_arc_hfr_120_dw9763 \
    libchromatix_ov12a10_arc_hfr_60 \
    libchromatix_ov12a10_arc_hfr_60_dw9763 \
    libchromatix_ov12a10_arc_hfr_90 \
    libchromatix_ov12a10_arc_hfr_90_dw9763 \
    libchromatix_ov12a10_arc_ofilm_4k_preview_dw9763 \
    libchromatix_ov12a10_arc_ofilm_4k_video_dw9763 \
    libchromatix_ov12a10_arc_ofilm_common \
    libchromatix_ov12a10_arc_ofilm_cpp_hfr_120 \
    libchromatix_ov12a10_arc_ofilm_cpp_hfr_60 \
    libchromatix_ov12a10_arc_ofilm_cpp_hfr_90 \
    libchromatix_ov12a10_arc_ofilm_cpp_liveshot \
    libchromatix_ov12a10_arc_ofilm_cpp_preview \
    libchromatix_ov12a10_arc_ofilm_cpp_snapshot \
    libchromatix_ov12a10_arc_ofilm_cpp_snapshot_hht \
    libchromatix_ov12a10_arc_ofilm_cpp_video \
    libchromatix_ov12a10_arc_ofilm_cpp_video_4k \
    libchromatix_ov12a10_arc_ofilm_default_preview_dw9763 \
    libchromatix_ov12a10_arc_ofilm_default_video_dw9763 \
    libchromatix_ov12a10_arc_ofilm_hfr_120 \
    libchromatix_ov12a10_arc_ofilm_hfr_120_dw9763 \
    libchromatix_ov12a10_arc_ofilm_hfr_60 \
    libchromatix_ov12a10_arc_ofilm_hfr_60_dw9763 \
    libchromatix_ov12a10_arc_ofilm_hfr_90 \
    libchromatix_ov12a10_arc_ofilm_hfr_90_dw9763 \
    libchromatix_ov12a10_arc_ofilm_postproc \
    libchromatix_ov12a10_arc_ofilm_preview \
    libchromatix_ov12a10_arc_ofilm_snapshot \
    libchromatix_ov12a10_arc_ofilm_video_4k \
    libchromatix_ov12a10_arc_ofilm_zsl_preview_dw9763 \
    libchromatix_ov12a10_arc_ofilm_zsl_video_dw9763 \
    libchromatix_ov12a10_arc_postproc \
    libchromatix_ov12a10_arc_preview \
    libchromatix_ov12a10_arc_snapshot \
    libchromatix_ov12a10_arc_video_4k \
    libchromatix_ov12a10_arc_zsl_preview_dw9763 \
    libchromatix_ov12a10_arc_zsl_video_dw9763 \
    libchromatix_ov12a10_common \
    libchromatix_ov12a10_cpp_hfr_120 \
    libchromatix_ov12a10_cpp_hfr_60 \
    libchromatix_ov12a10_cpp_hfr_90 \
    libchromatix_ov12a10_cpp_liveshot \
    libchromatix_ov12a10_cpp_preview \
    libchromatix_ov12a10_cpp_snapshot \
    libchromatix_ov12a10_cpp_video \
    libchromatix_ov12a10_cpp_video_4k \
    libchromatix_ov12a10_default_preview_dw9763 \
    libchromatix_ov12a10_default_video_dw9763 \
    libchromatix_ov12a10_hfr_120 \
    libchromatix_ov12a10_hfr_120_dw9763 \
    libchromatix_ov12a10_hfr_60 \
    libchromatix_ov12a10_hfr_60_dw9763 \
    libchromatix_ov12a10_hfr_90 \
    libchromatix_ov12a10_hfr_90_dw9763 \
    libchromatix_ov12a10_postproc \
    libchromatix_ov12a10_preview \
    libchromatix_ov12a10_snapshot \
    libchromatix_ov12a10_video_4k \
    libchromatix_ov12a10_zsl_preview_dw9763 \
    libchromatix_ov12a10_zsl_video_dw9763 \
    libchromatix_ov13880_4k_preview_dw9763 \
    libchromatix_ov13880_4k_video_dw9763 \
    libchromatix_ov13880_arc_4k_preview_dw9763 \
    libchromatix_ov13880_arc_4k_video_dw9763 \
    libchromatix_ov13880_arc_common \
    libchromatix_ov13880_arc_cpp_hfr_120 \
    libchromatix_ov13880_arc_cpp_hfr_60 \
    libchromatix_ov13880_arc_cpp_hfr_90 \
    libchromatix_ov13880_arc_cpp_liveshot \
    libchromatix_ov13880_arc_cpp_preview \
    libchromatix_ov13880_arc_cpp_snapshot \
    libchromatix_ov13880_arc_cpp_snapshot_hht \
    libchromatix_ov13880_arc_cpp_video \
    libchromatix_ov13880_arc_cpp_video_4k \
    libchromatix_ov13880_arc_default_preview_dw9763 \
    libchromatix_ov13880_arc_default_video_dw9763 \
    libchromatix_ov13880_arc_hfr_120 \
    libchromatix_ov13880_arc_hfr_120_dw9763 \
    libchromatix_ov13880_arc_hfr_60 \
    libchromatix_ov13880_arc_hfr_60_dw9763 \
    libchromatix_ov13880_arc_hfr_90 \
    libchromatix_ov13880_arc_hfr_90_dw9763 \
    libchromatix_ov13880_arc_ofilm_4k_preview_dw9763 \
    libchromatix_ov13880_arc_ofilm_4k_video_dw9763 \
    libchromatix_ov13880_arc_ofilm_common \
    libchromatix_ov13880_arc_ofilm_cpp_hfr_120 \
    libchromatix_ov13880_arc_ofilm_cpp_hfr_60 \
    libchromatix_ov13880_arc_ofilm_cpp_hfr_90 \
    libchromatix_ov13880_arc_ofilm_cpp_liveshot \
    libchromatix_ov13880_arc_ofilm_cpp_preview \
    libchromatix_ov13880_arc_ofilm_cpp_snapshot \
    libchromatix_ov13880_arc_ofilm_cpp_snapshot_hht \
    libchromatix_ov13880_arc_ofilm_cpp_video \
    libchromatix_ov13880_arc_ofilm_cpp_video_4k \
    libchromatix_ov13880_arc_ofilm_default_preview_dw9763 \
    libchromatix_ov13880_arc_ofilm_default_video_dw9763 \
    libchromatix_ov13880_arc_ofilm_hfr_120 \
    libchromatix_ov13880_arc_ofilm_hfr_120_dw9763 \
    libchromatix_ov13880_arc_ofilm_hfr_60 \
    libchromatix_ov13880_arc_ofilm_hfr_60_dw9763 \
    libchromatix_ov13880_arc_ofilm_hfr_90 \
    libchromatix_ov13880_arc_ofilm_hfr_90_dw9763 \
    libchromatix_ov13880_arc_ofilm_postproc \
    libchromatix_ov13880_arc_ofilm_preview \
    libchromatix_ov13880_arc_ofilm_snapshot \
    libchromatix_ov13880_arc_ofilm_video_4k \
    libchromatix_ov13880_arc_ofilm_zsl_preview_dw9763 \
    libchromatix_ov13880_arc_ofilm_zsl_video_dw9763 \
    libchromatix_ov13880_arc_postproc \
    libchromatix_ov13880_arc_preview \
    libchromatix_ov13880_arc_snapshot \
    libchromatix_ov13880_arc_video_4k \
    libchromatix_ov13880_arc_zsl_preview_dw9763 \
    libchromatix_ov13880_arc_zsl_video_dw9763 \
    libchromatix_ov13880_common \
    libchromatix_ov13880_cpp_hfr_120 \
    libchromatix_ov13880_cpp_hfr_60 \
    libchromatix_ov13880_cpp_hfr_90 \
    libchromatix_ov13880_cpp_liveshot \
    libchromatix_ov13880_cpp_preview \
    libchromatix_ov13880_cpp_snapshot \
    libchromatix_ov13880_cpp_video \
    libchromatix_ov13880_cpp_video_4k \
    libchromatix_ov13880_default_preview_dw9763 \
    libchromatix_ov13880_default_video_dw9763 \
    libchromatix_ov13880_hfr_120 \
    libchromatix_ov13880_hfr_120_dw9763 \
    libchromatix_ov13880_hfr_60 \
    libchromatix_ov13880_hfr_60_dw9763 \
    libchromatix_ov13880_hfr_90 \
    libchromatix_ov13880_hfr_90_dw9763 \
    libchromatix_ov13880_postproc \
    libchromatix_ov13880_preview \
    libchromatix_ov13880_snapshot \
    libchromatix_ov13880_video_4k \
    libchromatix_ov13880_zsl_preview_dw9763 \
    libchromatix_ov13880_zsl_video_dw9763 \
    libchromatix_ov5675_qtech_common \
    libchromatix_ov5675_qtech_cpp_hfr_120 \
    libchromatix_ov5675_qtech_cpp_hfr_60 \
    libchromatix_ov5675_qtech_cpp_hfr_90 \
    libchromatix_ov5675_qtech_cpp_liveshot \
    libchromatix_ov5675_qtech_cpp_preview \
    libchromatix_ov5675_qtech_cpp_snapshot \
    libchromatix_ov5675_qtech_cpp_video \
    libchromatix_ov5675_qtech_default_preview_3a \
    libchromatix_ov5675_qtech_default_video \
    libchromatix_ov5675_qtech_default_video_3a \
    libchromatix_ov5675_qtech_hfr_120 \
    libchromatix_ov5675_qtech_hfr_120_3a \
    libchromatix_ov5675_qtech_hfr_60 \
    libchromatix_ov5675_qtech_hfr_60_3a \
    libchromatix_ov5675_qtech_hfr_90 \
    libchromatix_ov5675_qtech_hfr_90_3a \
    libchromatix_ov5675_qtech_liveshot \
    libchromatix_ov5675_qtech_postproc \
    libchromatix_ov5675_qtech_preview \
    libchromatix_ov5675_qtech_snapshot \
    libchromatix_ov5675_qtech_zsl_preview_3a \
    libchromatix_ov5675_qtech_zsl_video_3a \
    libchromatix_s5k5e8_ofilm_common \
    libchromatix_s5k5e8_ofilm_cpp_hfr_120 \
    libchromatix_s5k5e8_ofilm_cpp_hfr_60 \
    libchromatix_s5k5e8_ofilm_cpp_hfr_90 \
    libchromatix_s5k5e8_ofilm_cpp_liveshot \
    libchromatix_s5k5e8_ofilm_cpp_preview \
    libchromatix_s5k5e8_ofilm_cpp_snapshot \
    libchromatix_s5k5e8_ofilm_cpp_video \
    libchromatix_s5k5e8_ofilm_default_preview_3a \
    libchromatix_s5k5e8_ofilm_default_video \
    libchromatix_s5k5e8_ofilm_default_video_3a \
    libchromatix_s5k5e8_ofilm_hfr_120 \
    libchromatix_s5k5e8_ofilm_hfr_120_3a \
    libchromatix_s5k5e8_ofilm_hfr_60 \
    libchromatix_s5k5e8_ofilm_hfr_60_3a \
    libchromatix_s5k5e8_ofilm_hfr_90 \
    libchromatix_s5k5e8_ofilm_hfr_90_3a \
    libchromatix_s5k5e8_ofilm_liveshot \
    libchromatix_s5k5e8_ofilm_postproc \
    libchromatix_s5k5e8_ofilm_preview \
    libchromatix_s5k5e8_ofilm_snapshot \
    libchromatix_s5k5e8_ofilm_zsl_preview_3a \
    libchromatix_s5k5e8_ofilm_zsl_video_3a \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_dcrf \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_modules \
    libmmcamera_arc_ofilm_ov12a10_eeprom \
    libmmcamera_arc_ofilm_ov13880_eeprom \
    libmmcamera_arc_ov12a10_eeprom \
    libmmcamera_arc_ov13880_eeprom \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_dcrf_lib \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_ofilm_s5k5e8_eeprom \
    libmmcamera_ov12a10 \
    libmmcamera_ov12a10_eeprom \
    libmmcamera_ov13880 \
    libmmcamera_ov13880_eeprom \
    libmmcamera_ov5675_qtech \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_qtech_ov5675_eeprom \
    libmmcamera_quadracfa \
    libmmcamera_s5k5e8_ofilm \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    consumerir.default \
    fingerprint.fpc.default \
    gf_fingerprint.goodix.default \
    libgf_algo \
    libgf_ca \
    libgf_hal \
    libgoodixfingerprintd_binder \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    libvendor.goodix.hardware.fingerprint@1.0 \
    com.fingerprints.extension \
    mm-qcamera-daemon
